services:
  - type: web
    name: ylori-ai-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port=$PORT --server.address=0.0.0.0
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
